version: "3"

services:
    minecraft:
        image: itzg/minecraft-server:latest
        container_name: minecraft_server
        ports:
            - "25565:25565"
        environment:
            EULA: "TRUE"
        volumes:
            - ~/minecraft_server/data:/data
        restart: always
