version: "3"

services:
    minecraft:
        build: .
        ports:
            - "25565:25565"
        volumes:
            - ./data:/minecraft
        command: java -Xms1G -Xmx2G -jar forge-1.16.5-36.1.0.jar nogui
